support new event version
kubesphere/kube-events pull request #171
Opened 2024-08-07 01:53 UTC by Gentleelephant

* 支持导出新事件，设置 `newEventType` 参数为 `true` 开启，默认为 `false`
* 定时获取 cluster name

旧版事件输出
```json
{"metadata":{"name":"ks-apiserver-7b94f9bd6f-vbtfp.17e9145e250bdcef","namespace":"kubesphere-system","uid":"40fa04c5-66f2-4c6e-8201-3b13b17dbc35","resourceVersion":"8460007","creationTimestamp":"2024-08-06T07:52:07Z"},"involvedObject":{"kind":"Pod","namespace":"kubesphere-system","name":"ks-apiserver-7b94f9bd6f-vbtfp","uid":"0ec6bbc8-9ba1-42f9-87b0-0dcfa99c0c57","apiVersion":"v1","resourceVersion":"8305839"},"reason":"FailedScheduling","message":"0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules.","source":{},"firstTimestamp":null,"lastTimestamp":null,"type":"Warning","eventTime":"2024-08-06T07:52:07.026936Z","series":{"count":1013,"lastObservedTime":"2024-08-07T01:32:29.267628Z"},"action":"Scheduling","reportingComponent":"default-scheduler","reportingInstance":"default-scheduler-i-bhbpy0xx","cluster":"host"}
```
新版事件输出
```json
{"metadata":{"name":"ks-apiserver-7b94f9bd6f-vbtfp.17e9145e250bdcef","namespace":"kubesphere-system","uid":"40fa04c5-66f2-4c6e-8201-3b13b17dbc35","resourceVersion":"8460007","creationTimestamp":"2024-08-06T07:52:07Z"},"eventTime":"2024-08-06T07:52:07.026936Z","series":{"count":1013,"lastObservedTime":"2024-08-07T01:32:29.267628Z"},"reportingController":"default-scheduler","reportingInstance":"default-scheduler-i-bhbpy0xx","action":"Scheduling","reason":"FailedScheduling","regarding":{"kind":"Pod","namespace":"kubesphere-system","name":"ks-apiserver-7b94f9bd6f-vbtfp","uid":"0ec6bbc8-9ba1-42f9-87b0-0dcfa99c0c57","apiVersion":"v1","resourceVersion":"8305839"},"note":"0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules.","type":"Warning","deprecatedSource":{},"deprecatedFirstTimestamp":null,"deprecatedLastTimestamp":null,"cluster":"host"}
```

2024-08-07 01:55 UTC, Gentleelephant commented
@benjaminhuo @wanjunlei

2024-08-07 01:56 UTC, benjaminhuo commented
@junotx @wanjunlei pls help to review

2024-08-08 02:21 UTC, wanjunlei requested changes

2024-08-08 02:21 UTC, wanjunlei commented on pkg/util/annoutil.go
> +		klog.Errorf("get namespace kubesphere-system error: %s", err)
The function needs to exit here, otherwise, ns will be nil and the following code will report an error.

2024-08-08 02:21 UTC, wanjunlei commented on pkg/exporter/kube_events_exporter.go
> +	"github.com/kubesphere/kube-events/pkg/util"
imports not sort

2024-08-08 02:21 UTC, wanjunlei commented
The ruler should be changed too.

2024-08-12 07:32 UTC, benjaminhuo commented
![image](https://github.com/user-attachments/assets/ea4a1dbf-192f-4fde-b653-546e3c49eca9)

字段都不太一样了，如果要真正完全支持，还要改 vector 配置 和 WhizardTelemetry 平台服务查 OpenSearch 的代码？

2024-08-12 07:39 UTC, benjaminhuo commented on pkg/exporter/kube_events_exporter.go
> +	v1 "k8s.io/api/events/v1"
```suggestion
	eventsv1 "k8s.io/api/events/v1"
```

2024-08-12 07:57 UTC, Gentleelephant commented
> ![image](https://private-user-images.githubusercontent.com/18525465/356965326-ea4a1dbf-192f-4fde-b653-546e3c49eca9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDk2NjcsIm5iZiI6MTcyMzQ0OTM2NywicGF0aCI6Ii8xODUyNTQ2NS8zNTY5NjUzMjYtZWE0YTFkYmYtMTkyZi00ZmRlLWI2NTMtNTQ2ZTNjNDllY2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA3NTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZjZkNDhlY2FhNDRmMWIxYWM4YzNmMjU4NmI5YTBjNzc5MTYwZWNjNzZlZTE4YWQxM2ZiNDEyNWRjYzRhZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._bON8_nWbKoFsbsHih547ZVBhb2UcamMlVWc6znpQyM)
> 
> 字段都不太一样了，如果要真正完全支持，还要改 vector 配置 和 WhizardTelemetry 平台服务查 OpenSearch 的代码？


完全配置，以后肯定得改

2024-08-12 08:02 UTC, junotx commented
the arg name is still `newEventType` which may be renamed as wanjun comments. the - separator instead of hump form is advised

2024-08-12 10:13 UTC, benjaminhuo commented on pkg/util/annoutil.go
> +		select {
成功一次还需要继续 loop 吗
民生银行那个是怎么出错的可以重现吗，他的情况我理解如果第一次没有成功，retry 到成功就可以了。

会有 cluster 改名的情况吗，很少吧

@wanjunlei @Gentleelephant

2024-10-09 02:11 UTC, benjaminhuo approved these changes

2024-10-09 02:11 UTC, merged