add the ci build
kubesphere/kube-events pull request #32
Opened 2022-03-07 10:53 UTC by wenchajun

This PR will configure the ability to automatically package images to dockerhub, but first, you need to configure  `secrets.REGISTRY_USER` and `secrets.REGISTRY_PASSWORD`    fields.
fix https://github.com/kubesphere/kube-events/issues/30

Signed-off-by: chengdehao <wenchajun@gmail.com>

2022-03-08 02:34 UTC, junotx requested changes

2022-03-08 02:34 UTC, junotx commented on .github/workflows/build-exporter-image.yaml
> +      - "cmd/operator/**"
Here may be `cmd/exporter/**`

2022-03-08 02:34 UTC, junotx commented on .github/workflows/build-ruler-image.yaml
> +      - "cmd/operator/**"
Here may be `cmd/ruler/**`

2022-03-08 02:38 UTC, zhu733756 commented on .github/workflows/build-exporter-image.yaml
> +          make cross-build-exporter -e REPO_EXPORTER=${{ env.REPO_EXPORTER }}/kube-events-exporter
` docker run --rm --privileged multiarch/qemu-user-static --reset -p yes` would be useful for custom building, I think it integrating it in the Makefile is suitable.

2022-03-08 02:50 UTC, zhu733756 commented on .github/workflows/build-exporter-image.yaml
> +          make cross-build-exporter -e REPO_EXPORTER=${{ env.REPO_EXPORTER }}/kube-events-exporter
> or use this action [docker/setup-qemu-action](https://github.com/docker/setup-qemu-action) instead

Yeah. I am confusing about that some image like fluentd perhaps not supported this action, refer to https://github.com/fluent/fluentd-docker-image/blob/master/v0.14/debian-onbuild/hooks/post_push.  Maybe we need a test for it. For common speaking, this action would support.

2022-03-08 10:09 UTC, junotx commented
/lgtm

2022-03-09 02:54 UTC, benjaminhuo approved these changes

2022-03-09 02:54 UTC, merged